;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.bb.help.-requirer
  (:require
    #?(:clj protosens.bb.help)
    #?(:clj protosens.bb.help.print)
))


;;;;;;;;;;


(defn -main [& _arg+])
