;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.maestro.-requirer
  (:require
    #?(:clj protosens.maestro)
    #?(:clj protosens.maestro.aggr)
    #?(:clj protosens.maestro.module.expose)
    #?(:clj protosens.maestro.module.requirer)
    #?(:clj protosens.maestro.module.uber)
    #?(:clj protosens.maestro.process)
))


;;;;;;;;;;


(defn -main [& _arg+])
