;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.maestro.main
  (:require
    #?(:clj protosens.maestro)
    #?(:clj protosens.maestro.aggr)
    #?(:clj protosens.maestro.git.lib)
    #?(:clj protosens.maestro.process)
    #?(:clj protosens.maestro.requirer)
    #?(:clj protosens.maestro.uber)
))


;;;;;;;;;;


(defn -main [& arg+] true)
