;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.classpath.-requirer
  (:require
    protosens.classpath
))


;;;;;;;;;;


(defn -main [& _arg+])
