;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.maestro.plugin.clj-kondo.-requirer
  (:require
    #?(:clj protosens.maestro.plugin.clj-kondo)
))


;;;;;;;;;;


(defn -main [& _arg+])
