;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.string.-requirer
  (:require
    #?(:clj protosens.string)
))


;;;;;;;;;;


(defn -main [& _arg+])
