;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.symbol.-requirer
  (:require
    #?(:clj protosens.symbol)
))


;;;;;;;;;;


(defn -main [& _arg+])
