;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.git.-requirer
  (:require
    #?(:clj protosens.git)
))


;;;;;;;;;;


(defn -main [& _arg+])
