;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.namespace.-requirer
  (:require
    #?(:clj protosens.namespace)
))


;;;;;;;;;;


(defn -main [& _arg+])
