;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.maestro.idiom.-requirer
  (:require
    #?(:clj protosens.maestro.idiom.changelog)
    #?(:clj protosens.maestro.idiom.listing)
    #?(:clj protosens.maestro.idiom.readme)
    #?(:clj protosens.maestro.idiom.stable)
))


;;;;;;;;;;


(defn -main [& _arg+])
