;; This file has been autogenerated.
;; Its only purpose is to require a collection of namespaces.
;;
;;
(ns ^{:no-doc true} protosens.edn.-requirer
  (:require
    #?(:clj protosens.edn.read)
))


;;;;;;;;;;


(defn -main [& _arg+])
